### ISSUE TITLE
Crash while trying to swipe on table cell

### ISSUE THREAD

**Issue by purepure** [andreamazz/AMWaveTransition#16] opened 2014-10-18 16:11 UTC
Your anim is really cool, I love its and would like to integrate into my project. Everything is ok, but while I trying to swipe quickly on table view cell, it crash. Here is the log and screenshot

![screen shot 2014-10-18 at 11 16 34 pm](https://cloud.githubusercontent.com/assets/3175469/4690306/a6882924-56e2-11e4-9860-9c1cd2e09dea.png)

```objc
Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI objectAtIndex:]: index 4294967295 beyond bounds [0 .. 0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x01476df6 __exceptionPreprocess + 182
	1   libobjc.A.dylib                     0x01100a97 objc_exception_throw + 44
	2   CoreFoundation                      0x0135a1b2 -[__NSArrayI objectAtIndex:] + 210
	3   CoreFoundation                      0x013c5538 -[NSArray objectAtIndexedSubscript:] + 40
	4                               0x00076562 -[AMWaveTransition handlePan:] + 562
	5   UIKit                               0x01c65d27 _UIGestureRecognizerSendActions + 327
	6   UIKit                               0x01c645a4 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 561
	7   UIKit                               0x01c665ed -[UIGestureRecognizer _delayedUpdateGesture] + 60
	8   UIKit                               0x01c69f6a ___UIGestureRecognizerUpdate_block_invoke661 + 57
	9   UIKit                               0x01c69e2d _UIGestureRecognizerRemoveObjectsFromArrayAndApplyBlocks + 317
	10  UIKit                               0x01c5dd36 _UIGestureRecognizerUpdate + 3720
	11  UIKit                               0x0187971b -[UIWindow _sendGesturesForEvent:] + 1356
	12  UIKit                               0x0187a57f -[UIWindow sendEvent:] + 769
	13  UIKit                               0x0183faa9 -[UIApplication sendEvent:] + 242
	14  UIKit                               0x0184f8de _UIApplicationHandleEventFromQueueEvent + 20690
	15  UIKit                               0x01824079 _UIApplicationHandleEventQueue + 2206
	16  CoreFoundation                      0x0139a7bf __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
	17  CoreFoundation                      0x013902cd __CFRunLoopDoSources0 + 253
	18  CoreFoundation                      0x0138f828 __CFRunLoopRun + 952
	19  CoreFoundation                      0x0138f1ab CFRunLoopRunSpecific + 443
	20  CoreFoundation                      0x0138efdb CFRunLoopRunInMode + 123
	21  GraphicsServices                    0x0480224f GSEventRunModal + 192
	22  GraphicsServices                    0x0480208c GSEventRun + 104
	23  UIKit                               0x01827e16 UIApplicationMain + 1526
	24  Funclip                             0x0002c7ad main + 141
	25  libdyld.dylib                       0x0319dac9 start + 1
	26  ???                                 0x00000001 0x0 + 1
)
```

Hope you can take a look and fix
Thank

**Comment by andreamazz** [comment] 2015-05-08 09:26
Closing this since I got no further feedback. Feel free to reopen it if the issue is still present.

**Closed by andreamazz** 2015-05-08 09:26 UTC
Labels: awaiting feedback
